### ISSUE TITLE
Why the results are different from the readme.md?

### ISSUE THREAD

**Issue by Amy2017new** [tapilab/sclust#2]
After installing the package, i try to test the package, but the results seem to be wrong. What should I do?
$ cat tmp/foo | sclust
0	Hi there, how are you?	-
1	hi where how you are	-
2	i like to sing	-
3	I am going to sing	-
4	hi where how you are	-
5	hi there how...	-
6	do you sing???	-

$ cat tmp/foo | sclust | sclust-summarize  -k 3
---------7 documents, 7 clusters---------
1	1	hi where how you are	-
1	0	Hi there, how are you?	-
1	3	I am going to sing	-
1	2	i like to sing	-
1	5	hi there how...	-
1	4	hi where how you are	-
1	6	do you sing???	-

**Comment by aronwc** [comment]
Not sure. Maybe try changing the similarity threshold:
`cat /tmp/foo | sclust -t .1`

Also, the pip version may be out of date, so you can install from master by
`pip install git+https://github.com/tapilab/sclust`

Best,
Aron

**Comment by ghost** [comment]
Hi, i encounter the same problem , have you solved it?

**Comment by Sakuragizwy** [comment]
Hi, i encounter the same problem , have you solved it?

**Comment by aronwc** [comment]
I've rerun and updated the README
6263204bb55e586a618f326b9ec16eb18b238aeb
